export const REFUND_BANKS = Object.freeze([
  { code: "39", name: "경남은행", group: "지방은행" },
  { code: "34", name: "광주은행", group: "지방은행" },
  { code: "12", name: "단위농협(지역농축협)", group: "농협/수협" },
  { code: "32", name: "부산은행", group: "지방은행" },
  { code: "45", name: "새마을금고", group: "상호금융" },
  { code: "64", name: "산림조합", group: "상호금융" },
  { code: "88", name: "신한은행", group: "시중은행" },
  { code: "48", name: "신협", group: "상호금융" },
  { code: "27", name: "씨티은행", group: "시중은행" },
  { code: "20", name: "우리은행", group: "시중은행" },
  { code: "71", name: "우체국예금보험", group: "기타 은행" },
  { code: "50", name: "저축은행중앙회", group: "기타 은행" },
  { code: "37", name: "전북은행", group: "지방은행" },
  { code: "35", name: "제주은행", group: "지방은행" },
  { code: "90", name: "카카오뱅크", group: "인터넷전문은행" },
  { code: "89", name: "케이뱅크", group: "인터넷전문은행" },
  { code: "92", name: "토스뱅크", group: "인터넷전문은행" },
  { code: "81", name: "하나은행", group: "시중은행" },
  { code: "54", name: "홍콩상하이은행", group: "외국 은행" },
  { code: "60", name: "Bank of America", group: "외국 은행" },
  { code: "03", name: "IBK기업은행", group: "특수은행" },
  { code: "06", name: "KB국민은행", group: "시중은행" },
  { code: "31", name: "iM뱅크(대구)", group: "지방은행" },
  { code: "02", name: "한국산업은행", group: "특수은행" },
  { code: "11", name: "NH농협은행", group: "농협/수협" },
  { code: "23", name: "SC제일은행", group: "시중은행" },
  { code: "07", name: "Sh수협은행", group: "농협/수협" },
  { code: "30", name: "수협중앙회", group: "농협/수협" },
]);

export const REFUND_BANK_GROUPS = Object.freeze([
  "시중은행",
  "특수은행",
  "지방은행",
  "인터넷전문은행",
  "농협/수협",
  "상호금융",
  "기타 은행",
  "외국 은행",
]);
