/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  // Classes composed from runtime values (e.g. `bg-${color}/10`, `text-${color}`)
  // are invisible to the JIT scanner, so list their variants explicitly.
  safelist: [
    "text-status-available", "text-status-pending", "text-status-assigned", "text-status-blocked", "text-status-visited",
    "bg-status-available", "bg-status-pending", "bg-status-assigned", "bg-status-blocked", "bg-status-visited",
    "bg-status-available/10", "bg-status-pending/10", "bg-status-assigned/10", "bg-status-blocked/10", "bg-status-visited/10",
    "bg-status-available/5",
    "shadow-status-available/20",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#00458e",
        "surface-container-low": "#f6f3f5",
        "on-primary-fixed": "#001b3e",
        "surface-bright": "#fcf8fb",
        "surface-dim": "#dcd9dc",
        background: "#fcf8fb",
        "secondary-container": "#e2dfe1",
        "on-secondary-fixed": "#1b1b1d",
        "primary-container": "#0066cc",
        "tertiary-container": "#67686a",
        "primary-on-dark": "#2997ff",
        "on-background": "#1b1b1d",
        hairline: "#e0e0e0",
        "divider-soft": "#f0f0f0",
        "on-error": "#ffffff",
        "inverse-primary": "#aac7ff",
        "surface-tile-dark": "#272729",
        "on-primary-container": "#dfe8ff",
        "on-tertiary-fixed-variant": "#454749",
        "secondary-fixed": "#e4e2e4",
        "tertiary-fixed": "#e2e2e4",
        "surface-container-high": "#eae7ea",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f3f0f2",
        "on-surface-variant": "#414753",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c8",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c6c6c8",
        "inverse-surface": "#303032",
        "ink-muted": "#7a7a7a",
        outline: "#727784",
        error: "#ba1a1a",
        secondary: "#5f5e60",
        "on-primary": "#ffffff",
        "surface-pearl": "#fafafc",
        "surface-tint": "#005cba",
        "on-secondary-fixed-variant": "#474649",
        "on-error-container": "#93000a",
        surface: "#fcf8fb",
        "surface-container-highest": "#e4e2e4",
        "surface-container": "#f0edef",
        "primary-focus": "#0071e3",
        "primary-fixed-dim": "#aac7ff",
        "outline-variant": "#c1c6d5",
        "on-tertiary-fixed": "#1a1c1d",
        "surface-variant": "#e4e2e4",
        primary: "#004e9f",
        "on-surface": "#1b1b1d",
        "on-tertiary-container": "#e8e8ea",
        tertiary: "#4e5052",
        "primary-fixed": "#d7e3ff",
        "surface-tile-dark-alt": "#2a2a2c",
        "on-secondary-container": "#636264",
        "status-available": "#34c759",
        "status-pending": "#ff9500",
        "status-assigned": "#0066cc",
        "status-blocked": "#8e8e93",
        "status-visited": "#ff3b30",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        xxl: "48px",
        xl: "32px",
        section: "80px",
        xxs: "4px",
        sm: "12px",
        md: "17px",
        xs: "8px",
      },
      fontFamily: {
        "nav-link": ["Noto Sans KR", "sans-serif"],
        "hero-display": ["Hanken Grotesk", "sans-serif"],
        "button-large": ["Noto Sans KR", "sans-serif"],
        "display-md": ["Hanken Grotesk", "sans-serif"],
        body: ["Noto Sans KR", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        tagline: ["Hanken Grotesk", "sans-serif"],
        caption: ["Noto Sans KR", "sans-serif"],
        "body-strong": ["Noto Sans KR", "sans-serif"],
        lead: ["Noto Sans KR", "sans-serif"],
      },
      fontSize: {
        "nav-link": ["12px", { lineHeight: "1.0", letterSpacing: "-0.01em", fontWeight: "400" }],
        "hero-display": ["56px", { lineHeight: "1.07", letterSpacing: "-0.02em", fontWeight: "600" }],
        "button-large": ["18px", { lineHeight: "1.0", letterSpacing: "0", fontWeight: "400" }],
        "display-md": ["34px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        body: ["17px", { lineHeight: "1.47", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.15", letterSpacing: "0", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "600" }],
        tagline: ["21px", { lineHeight: "1.19", letterSpacing: "0.01em", fontWeight: "600" }],
        caption: ["14px", { lineHeight: "1.43", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-strong": ["17px", { lineHeight: "1.24", letterSpacing: "-0.01em", fontWeight: "600" }],
        lead: ["28px", { lineHeight: "1.14", letterSpacing: "0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
