apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventoday-be
  namespace: eventoday
  labels:
    app: eventoday-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventoday-be
  template:
    metadata:
      labels:
        app: eventoday-be
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: eventoday-be
          image: ghcr.io/half-fifty/eventoday-be:151b7f43899389f1ad4b59f5a441d7e1cf3843b2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: DB_URL
              value: "jdbc:postgresql://10.0.0.31:5432/expo_platform"
            - name: REDIS_HOST
              value: "10.0.0.31"
            - name: REDIS_PORT
              value: "6379"
          envFrom:
            - secretRef:
                name: eventoday-secret
---
apiVersion: v1
kind: Service
metadata:
  name: eventoday-be
  namespace: eventoday
spec:
  selector:
    app: eventoday-be
  ports:
    - port: 8080
      targetPort: 8080
