apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventoday-be
  namespace: eventoday
  labels:
    app: eventoday-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventoday-be
  template:
    metadata:
      labels:
        app: eventoday-be
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: eventoday-be
          image: ghcr.io/half-fifty/eventoday-be:b81994798b240bf6c00fcda6774547653e011cb6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              memory: 768Mi
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 15
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: DB_URL
              value: "jdbc:postgresql://10.0.0.31:5432/expo_platform"
            - name: REDIS_HOST
              value: "10.0.0.31"
            - name: REDIS_PORT
              value: "6379"
          envFrom:
            - secretRef:
                name: eventoday-secret
---
apiVersion: v1
kind: Service
metadata:
  name: eventoday-be
  namespace: eventoday
spec:
  selector:
    app: eventoday-be
  ports:
    - port: 8080
      targetPort: 8080
