apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventoday-fe
  namespace: eventoday
  labels:
    app: eventoday-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventoday-fe
  template:
    metadata:
      labels:
        app: eventoday-fe
    spec:
      containers:
        - name: eventoday-fe
          image: ghcr.io/half-fifty/eventoday-fe:d5beb6b5ba7662a7ae7adef92a003a347a84f879
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eventoday-fe
  namespace: eventoday
spec:
  selector:
    app: eventoday-fe
  ports:
    - port: 80
      targetPort: 80
