package com.min.edu.payment.domain;

public enum PaymentAuditEventType {
    PAYMENT_WAITING_FOR_DEPOSIT,
    PAYMENT_PAID,
    PAYMENT_EXPIRED,
    PAYMENT_REFUNDED,
    REFUND_REQUESTED,
    REFUND_FAILED,
    REFUND_COMPLETED,
    REFUND_AMBIGUOUS,
    VA_RECONCILIATION_REPAIRED,
    VA_RECONCILIATION_INVESTIGATE
}
