package com.min.edu.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum GlobalErrorCode implements ErrorCode {

    ADMISSION_CHECK_IN_INVALID_STATE(HttpStatus.CONFLICT, "ADMISSION_409_015", "현재 상태에서는 입장 처리할 수 없습니다."),
    ADMISSION_CHECK_IN_DUPLICATE(HttpStatus.CONFLICT, "ADMISSION_409_016", "이미 입장 처리된 티켓입니다."),
    ADMISSION_CHECK_IN_EVENT_MISMATCH(HttpStatus.FORBIDDEN, "ADMISSION_403_003", "해당 행사의 입장 QR이 아닙니다."),
    ADMISSION_CHECK_IN_CANCEL_INVALID_STATE(HttpStatus.CONFLICT, "ADMISSION_409_017", "현재 상태에서는 입장 처리를 취소할 수 없습니다."),
    ADMISSION_CHECK_IN_PROCESSING_CONFLICT(HttpStatus.CONFLICT, "ADMISSION_409_018", "현재 입장 처리를 진행하고 있습니다. 잠시 후 다시 시도해주세요."),

    EXCHANGE_CODE_NOT_FOUND(HttpStatus.NOT_FOUND, "ADMISSION_404_003", "교환 코드를 찾을 수 없습니다."),
    ADMISSION_TICKET_NOT_FOUND(HttpStatus.NOT_FOUND, "ADMISSION_404_004", "입장 티켓을 찾을 수 없습니다."),
    EXCHANGE_CODE_INVALID_STATE(HttpStatus.CONFLICT, "ADMISSION_409_010", "사용할 수 없는 교환 코드입니다."),
    EXCHANGE_CODE_EXPIRED(HttpStatus.CONFLICT, "ADMISSION_409_011", "만료된 교환 코드입니다."),
    EXCHANGE_CODE_EVENT_NOT_REDEEMABLE(HttpStatus.CONFLICT, "ADMISSION_409_012", "교환 코드를 사용할 수 없는 행사입니다."),
    EXCHANGE_CODE_HOLDER_MISMATCH(HttpStatus.FORBIDDEN, "ADMISSION_403_001", "교환 코드 소유자가 일치하지 않습니다."),
    EXCHANGE_CODE_GUEST_NOT_REDEEMABLE(HttpStatus.FORBIDDEN, "ADMISSION_403_002", "게스트 교환 코드는 이 API에서 사용할 수 없습니다."),
    ADMISSION_TICKET_ALREADY_EXISTS(HttpStatus.CONFLICT, "ADMISSION_409_013", "이미 입장 티켓이 발급된 교환 코드입니다."),
    ADMISSION_TICKET_QR_NOT_AVAILABLE(HttpStatus.CONFLICT, "ADMISSION_409_014", "현재 상태에서는 입장 QR을 조회할 수 없습니다."),
    ADMISSION_QR_TOKEN_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "ADMISSION_500_002", "입장 QR 토큰 생성에 실패했습니다."),
    ADMISSION_QR_IMAGE_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "ADMISSION_500_003", "입장 QR 이미지 생성에 실패했습니다."),

    EXCHANGE_CODE_REQUEST_ALREADY_ISSUED(HttpStatus.CONFLICT, "ADMISSION_409_005", "이미 발급 완료된 교환 코드 요청입니다."),
    EXCHANGE_CODE_REQUEST_ISSUANCE_INCONSISTENT(HttpStatus.CONFLICT, "ADMISSION_409_006", "교환 코드 발급 데이터가 일치하지 않습니다."),
    EXCHANGE_CODE_REQUEST_RECIPIENT_NOT_FOUND(HttpStatus.NOT_FOUND, "ADMISSION_404_002", "교환 코드 발급 메일 수신자를 찾을 수 없습니다."),
    EXCHANGE_CODE_REQUEST_RECIPIENT_EMAIL_MISSING(HttpStatus.CONFLICT, "ADMISSION_409_007", "교환 코드 발급 메일 수신자 이메일이 없습니다."),
    EXCHANGE_CODE_REQUEST_EVENT_ENDED(HttpStatus.CONFLICT, "ADMISSION_409_008", "종료된 행사에는 교환 코드를 발급할 수 없습니다."),
    EXCHANGE_CODE_REQUEST_EMAIL_ALREADY_SENT(HttpStatus.CONFLICT, "ADMISSION_409_009", "이미 교환 코드 발급 메일을 발송했습니다."),




    KAKAO_MAP_API_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "EVENT_503_001", "카카오 장소 검색 서비스를 이용할 수 없습니다."),

    INVALID_INPUT_VALUE(HttpStatus.BAD_REQUEST, "COMMON_400", "요청 값이 올바르지 않습니다."),
    UNSUPPORTED_OAUTH_PROVIDER(HttpStatus.BAD_REQUEST, "AUTH_400_001", "지원하지 않는 OAuth 제공자입니다."),
    OAUTH_REQUIRED_ATTRIBUTE_MISSING(HttpStatus.BAD_REQUEST, "AUTH_400_002", "소셜 로그인 사용자 정보가 부족합니다."),
    BUSINESS_VERIFICATION_FAILED(HttpStatus.BAD_REQUEST, "ORGANIZATION_400_001", "사업자 정보가 일치하지 않습니다."),
    BUSINESS_NOT_ACTIVE(HttpStatus.BAD_REQUEST, "ORGANIZATION_400_002", "현재 영업 중인 사업자만 가입할 수 있습니다."),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "COMMON_401", "인증이 필요합니다."),
    REFRESH_TOKEN_REQUIRED(HttpStatus.UNAUTHORIZED, "AUTH_401_001", "Refresh Token이 필요합니다."),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH_401_002", "유효하지 않은 Refresh Token입니다."),
    REFRESH_TOKEN_MISMATCH(HttpStatus.UNAUTHORIZED, "AUTH_401_003", "로그인 정보가 만료되었습니다."),
    OAUTH_LOGIN_FAILED(HttpStatus.UNAUTHORIZED, "AUTH_401_010", "소셜 로그인에 실패했습니다."),
    INVALID_BUSINESS_CREDENTIALS(HttpStatus.UNAUTHORIZED, "AUTH_401_011", "사업자등록번호 또는 비밀번호가 올바르지 않습니다."),
    FORBIDDEN(HttpStatus.FORBIDDEN, "COMMON_403", "접근 권한이 없습니다."),
    MEMBER_LOGIN_RESTRICTED(HttpStatus.FORBIDDEN, "AUTH_403_001", "로그인이 제한된 회원입니다."),
    OAUTH_EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN, "AUTH_403_002", "검증된 이메일로만 소셜 로그인을 이용할 수 있습니다."),
    ORDER_ACCESS_TOKEN_REQUIRED(HttpStatus.UNAUTHORIZED, "TICKET_401_001", "주문 접근 토큰이 필요합니다."),
    ORDER_ACCESS_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "TICKET_401_002", "주문 접근 토큰이 유효하지 않습니다."),
    ORDER_ACCESS_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "TICKET_401_003", "주문 접근 토큰이 만료되었습니다."),
    ORDER_ACCESS_DENIED(HttpStatus.FORBIDDEN, "TICKET_403_001", "주문 조회 권한이 없습니다."),
    BUSINESS_NUMBER_ALREADY_REGISTERED(HttpStatus.CONFLICT, "ORGANIZATION_409_001", "이미 가입된 사업자등록번호입니다."),
    MEMBER_EMAIL_ALREADY_REGISTERED(HttpStatus.CONFLICT, "MEMBER_409_001", "이미 사용 중인 이메일입니다."),
    BUSINESS_SIGNUP_CONFLICT(HttpStatus.CONFLICT, "ORGANIZATION_409_002", "사업자 가입 정보가 이미 사용 중입니다."),
    NTS_BUSINESS_API_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "ORGANIZATION_503_001", "사업자 정보 확인 서비스를 이용할 수 없습니다."),
    ORGANIZATION_REJECTION_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "ORGANIZATION_400_003", "반려 사유를 입력해 주세요."),
    ORGANIZATION_APPROVAL_PENDING(HttpStatus.FORBIDDEN, "ORGANIZATION_403_001", "행사 개최자 가입 신청을 검토 중입니다. 승인 완료 후 로그인할 수 있습니다."),
    ORGANIZATION_SUSPENDED(HttpStatus.FORBIDDEN, "ORGANIZATION_403_003", "현재 이용이 정지된 조직입니다. 관리자에게 문의해 주세요."),
    ORGANIZATION_SIGNUP_REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "ORGANIZATION_404_001", "가입 심사 신청을 찾을 수 없습니다."),
    INVALID_GUEST_BUYER_INFO(HttpStatus.BAD_REQUEST, "TICKET_400_001", "비회원 구매자 정보가 올바르지 않습니다."),
    TICKET_PURCHASE_LIMIT_EXCEEDED(HttpStatus.UNPROCESSABLE_ENTITY, "TICKET_422_001", "티켓 구매 제한 수량을 초과했습니다."),
    TICKET_SALES_NOT_OPEN(HttpStatus.UNPROCESSABLE_ENTITY, "TICKET_422_002", "현재 티켓 판매 기간이 아닙니다."),
    TICKET_SOLD_OUT(HttpStatus.CONFLICT, "TICKET_409_001", "티켓 재고가 부족합니다."),
    ENTITY_NOT_FOUND(HttpStatus.NOT_FOUND, "COMMON_404", "요청한 리소스를 찾을 수 없습니다."),
    EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "EVENT_404_001", "행사를 찾을 수 없습니다."),
    TICKET_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "TICKET_404_002", "티켓 주문을 찾을 수 없습니다."),
    ORDER_NUMBER_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "TICKET_500_001", "주문번호 생성에 실패했습니다."),
    EXCHANGE_CODE_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "ADMISSION_500_001", "교환 코드 생성에 실패했습니다."),
    PAYMENT_AMOUNT_MISMATCH(HttpStatus.BAD_REQUEST, "PAYMENT_400_001", "결제 금액이 일치하지 않습니다."),
    PAYMENT_NOT_REQUIRED(HttpStatus.BAD_REQUEST, "PAYMENT_400_002", "결제가 필요하지 않은 주문입니다."),
    PAYMENT_CONFIRM_REJECTED(HttpStatus.BAD_REQUEST, "PAYMENT_400_003", "결제 승인이 거절되었습니다."),
    PAYMENT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "PAYMENT_403_001", "결제 처리 권한이 없습니다."),
    PAYMENT_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "PAYMENT_404_001", "결제 주문을 찾을 수 없습니다."),
    PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "PAYMENT_404_002", "결제 내역을 찾을 수 없습니다."),
    PAYMENT_INVALID_STATE(HttpStatus.CONFLICT, "PAYMENT_409_001", "결제할 수 없는 주문 상태입니다."),
    PAYMENT_ALREADY_PROCESSED(HttpStatus.CONFLICT, "PAYMENT_409_002", "이미 처리된 결제입니다."),
    PAYMENT_PROCESSING_CONFLICT(HttpStatus.CONFLICT, "PAYMENT_409_003", "현재 결제를 처리하고 있습니다. 잠시 후 다시 시도해주세요."),
    PAYMENT_DATA_INCONSISTENT(HttpStatus.CONFLICT, "PAYMENT_409_004", "결제 데이터가 일치하지 않습니다."),
    PAYMENT_KEY_ALREADY_USED(HttpStatus.CONFLICT, "PAYMENT_409_005", "이미 사용된 결제 키입니다."),
    PAYMENT_METHOD_MISMATCH(HttpStatus.BAD_REQUEST, "PAYMENT_400_004", "결제 수단이 일치하지 않습니다."),
    VIRTUAL_ACCOUNT_REQUIRED(HttpStatus.BAD_GATEWAY, "PAYMENT_502_003", "가상계좌 결제 정보가 부족합니다."),
    VIRTUAL_ACCOUNT_SECRET_MISMATCH(HttpStatus.FORBIDDEN, "PAYMENT_403_002", "가상계좌 결제 요청 검증에 실패했습니다."),
    REFUND_RECEIVE_ACCOUNT_REQUIRED(HttpStatus.BAD_REQUEST, "REFUND_400_002", "가상계좌 결제 환불 계좌 정보가 필요합니다."),
    REFUND_RECEIVE_ACCOUNT_INVALID(HttpStatus.BAD_REQUEST, "REFUND_400_003", "가상계좌 결제 환불 계좌 정보가 유효하지 않습니다."),
    PAYMENT_GATEWAY_ERROR(HttpStatus.BAD_GATEWAY, "PAYMENT_502_001", "결제 대행사 응답 처리에 실패했습니다."),
    PAYMENT_GATEWAY_RESPONSE_INVALID(HttpStatus.BAD_GATEWAY, "PAYMENT_502_002", "결제 대행사 응답이 유효하지 않습니다."),
    PAYMENT_GATEWAY_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "PAYMENT_504_001", "결제 대행사 응답 시간이 초과되었습니다."),
    REFUND_ACCESS_DENIED(HttpStatus.FORBIDDEN, "REFUND_403_001", "환불 접근 권한이 없습니다."),
    REFUND_NOT_FOUND(HttpStatus.NOT_FOUND, "REFUND_404_001", "환불 내역을 찾을 수 없습니다."),
    REFUND_NOT_ALLOWED(HttpStatus.CONFLICT, "REFUND_409_001", "환불할 수 없는 주문입니다."),
    REFUND_ALREADY_COMPLETED(HttpStatus.CONFLICT, "REFUND_409_002", "이미 완료된 환불입니다."),
    USED_TICKET_CANNOT_BE_REFUNDED(HttpStatus.CONFLICT, "REFUND_409_003", "사용된 티켓이 있어 환불할 수 없습니다."),
    REFUND_DATA_INCONSISTENT(HttpStatus.CONFLICT, "REFUND_409_004", "환불 데이터가 일치하지 않습니다."),
    REFUND_ALREADY_PROCESSING(HttpStatus.CONFLICT, "REFUND_409_005", "현재 환불을 처리하고 있습니다. 잠시 후 다시 시도해주세요."),
    REFUND_REJECTED(HttpStatus.BAD_REQUEST, "REFUND_400_001", "환불 요청이 거절되었습니다."),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON_500", "서버 내부 오류가 발생했습니다."),
    INVALID_FILE_TYPE(HttpStatus.BAD_REQUEST, "FILE_400_001", "허용되지 않는 파일 형식입니다."),
    FILE_SIZE_EXCEEDED(HttpStatus.BAD_REQUEST, "FILE_400_002", "파일 크기가 허용 한도를 초과했습니다."),
    FILE_NOT_FOUND(HttpStatus.NOT_FOUND, "FILE_404_001", "파일을 찾을 수 없습니다."),
    FILE_ACCESS_DENIED(HttpStatus.FORBIDDEN, "FILE_403_001", "파일에 접근할 권한이 없습니다."),
    FILE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE_500_001", "파일 업로드에 실패했습니다."),
    RECRUITMENT_PERIOD_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT_400_001", "모집 종료일은 시작일 이후여야 합니다."),
    RECRUITMENT_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, "RECRUITMENT_400_002", "이미 모집 공고가 등록된 행사입니다."),
    RECRUITMENT_STATUS_TRANSITION_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT_400_003", "허용되지 않는 상태 변경입니다."),
    BOOTH_DELETE_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "BOOTH_400_002", "사용 가능 상태인 부스만 삭제할 수 있습니다."),
    BOOTH_NOT_ASSIGNED(HttpStatus.BAD_REQUEST, "BOOTH_400_003", "배정된 부스만 소개를 등록할 수 있습니다."),
    BOOTH_STATUS_TRANSITION_INVALID(HttpStatus.BAD_REQUEST, "BOOTH_400_004", "허용되지 않는 부스 상태 변경입니다."),
    BOOTH_EVENT_MISMATCH(HttpStatus.BAD_REQUEST, "BOOTH_400_005", "해당 모집 공고의 행사에 속한 부스가 아닙니다."),
    RESERVATION_SLOT_TIME_CONFLICT(HttpStatus.CONFLICT, "BOOTH_409_001", "이미 존재하는 시간대입니다."),
    RESERVATION_SLOT_HAS_RESERVATIONS(HttpStatus.CONFLICT, "BOOTH_409_005", "예약 이력이 있는 시간대는 삭제할 수 없습니다. 대신 꺼주세요."),
    RESERVATION_ALREADY_EXISTS(HttpStatus.CONFLICT, "BOOTH_409_006", "이미 예약이 진행 중입니다."),
    BOOTH_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "BOOTH_409_002", "이미 등록된 부스 번호입니다."),
    VENUE_MAP_VERSION_CONFLICT(HttpStatus.CONFLICT, "BOOTH_409_007", "같은 평면도가 동시에 업로드되었습니다. 다시 시도해주세요."),
    BOOTH_QR_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "BOOTH_500_001", "QR 토큰 생성에 실패했습니다."),
    RECRUITMENT_NOT_OPEN(HttpStatus.UNPROCESSABLE_ENTITY, "BOOTH_422_001", "현재 부스 신청 모집 기간이 아닙니다."),
    BOOTH_REQUIREMENT_NOT_MET(HttpStatus.UNPROCESSABLE_ENTITY, "BOOTH_422_002", "요청한 설비를 해당 부스에서 제공하지 않습니다."),
    ESTIMATE_FILE_REQUIRED(HttpStatus.BAD_REQUEST, "BOOTH_400_001", "견적서 파일은 필수입니다."),
    BOOTH_NOT_AVAILABLE(HttpStatus.CONFLICT, "BOOTH_409_003", "해당 부스는 신청 가능한 상태가 아닙니다."),
    BOOTH_APPLICATION_CONFLICT(HttpStatus.CONFLICT, "BOOTH_409_004", "다른 신청에 의해 이미 처리되었습니다. 잠시 후 다시 시도해주세요."),
    APPLICATION_NUMBER_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "BOOTH_500_002", "신청번호 생성에 실패했습니다."),
    APPLICATION_CANNOT_BE_CANCELLED(HttpStatus.UNPROCESSABLE_ENTITY, "BOOTH_422_003", "현재 상태에서는 신청을 취소할 수 없습니다."),
    APPLICATION_REVIEW_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY, "BOOTH_422_004", "현재 상태에서는 검토를 시작할 수 없습니다."),
    APPLICATION_APPROVE_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY, "BOOTH_422_005", "현재 상태에서는 신청을 승인할 수 없습니다."),
    APPLICATION_REJECT_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY, "BOOTH_422_006", "현재 상태에서는 신청을 반려할 수 없습니다."),
    BUSINESS_NUMBER_REQUIRED_FOR_APPLICATION(HttpStatus.UNPROCESSABLE_ENTITY, "BOOTH_422_007", "사업자등록번호가 등록된 조직만 신청할 수 있는 모집 공고입니다."),
    RECRUITMENT_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "RECRUITMENT_409_001", "다른 요청에 의해 이미 처리되었습니다. 새로고침 후 다시 시도해주세요."),
    EXCHANGE_CODE_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "ADMISSION_404_001", "교환 코드 발급 요청을 찾을 수 없습니다."),
    EXCHANGE_CODE_REQUEST_ALREADY_EXISTS(HttpStatus.CONFLICT, "ADMISSION_409_001", "이미 처리 대기 중인 교환 코드 발급 요청이 있습니다."),
    EXCHANGE_CODE_REQUEST_INVALID_STATE(HttpStatus.CONFLICT, "ADMISSION_409_002", "현재 상태에서는 교환 코드 발급 요청을 심사할 수 없습니다."),
    EXCHANGE_CODE_REQUEST_EVENT_ALREADY_STARTED(HttpStatus.CONFLICT, "ADMISSION_409_003", "행사 티켓 운영 마감 이후에는 교환 코드 발급 요청을 생성할 수 없습니다."),
    EXCHANGE_CODE_REQUEST_EVENT_NOT_OPEN(HttpStatus.CONFLICT, "ADMISSION_409_004", "교환 코드 발급 요청이 가능한 행사 상태가 아닙니다."),
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND,"NOTIFICATION_404_001","알림을 찾을 수 없습니다."),
    EMAIL_SEND_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "MAIL_503_001", "이메일 발송 서비스를 일시적으로 이용할 수 없습니다."),
    // booth congestion 관련 에러
    BOOTH_NOT_FOUND(HttpStatus.NOT_FOUND, "BOOTH_404_001", "부스를 찾을 수 없습니다"),
    BOOTH_CONGESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "BOOTH_404_002", "부스 혼잡도 정보를 찾을 수 없습니다"),
    BOOTH_REVIEW_SUMMARY_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "BOOTH_503_001", "리뷰 요약 서비스를 이용할 수 없습니다."),
    VENUE_MAP_AUTO_LAYOUT_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "BOOTH_503_002", "평면도 자동 배치 제안 서비스를 이용할 수 없습니다.");




    private final HttpStatus status;
    private final String code;
    private final String message;


}
